name: Mirror "master" and "main" branches
on:
  push:
    branches:
      - master
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to "master"
        uses: zofrex/mirror-branch@ea152f124954fa4eb26eea3fe0dbe313a3a08d94
        with:
          target-branch: master
          force: true
      - name: Mirror to "main"
        uses: zofrex/mirror-branch@ea152f124954fa4eb26eea3fe0dbe313a3a08d94
        with:
          target-branch: main
          force: false
